services:
  php:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      COMPOSER_HOME: /tmp/composer
      DATABASE_URL: "postgresql://${POSTGRES_USER:-yousign}:${POSTGRES_PASSWORD:-123456789}@database:5432/${POSTGRES_DB:-gh-archive-keyword}?serverVersion=14&charset=utf8"
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer:4.7
    ports:
      - "${ADMINER_PORT:-8888}:8080"
    depends_on:
      - database
    restart: unless-stopped

volumes:
  postgres_data:
